### ISSUE TITLE
Music library not loading at all

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#34]
I uninstalled 0.1.4 and installed 0.1.5 and well... Nothing's loading now, at first it showed 0 songs loaded 0 seconds or something like that, but now "Nothing baking".

I tried drag and drop but it crashed the app...
Tried to reproduce this on mobile and it seems it isn't loading anything there either.

**Comment by DannyTalent** [comment]
Still present in 0.1.6...
Uninstalled 0.1.5 and when I selected my music folder, no songs were loaded

**Comment by theweavrs** [comment]
Have you tried drag and dropping songs into library? I am not experiencing this issue.

**Comment by theweavrs** [comment]
Try resetting the player and loading the library again. See if it occurs.

**Comment by theweavrs** [comment]
@DannyTalent I fixed the other two issues and tweaked this one a bit.

Try the update: [Alpha-1.6.1](https://github.com/theweavrs/BreadPlayer/releases/tag/v0.1.6.1-alpha)

**Comment by DannyTalent** [comment]
![image](https://cloud.githubusercontent.com/assets/23058301/20254003/689d186a-a9fe-11e6-9d91-bc5c51ccaf06.png)
Nope

And I swear I do have songs in there!
![image](https://cloud.githubusercontent.com/assets/23058301/20254008/77e9c020-a9fe-11e6-8b94-913c598fd1d9.png)
Drag and drop seems to work fine.. Though I dragged the whole folder and got this (after dragging 21 Guns)

![image](https://cloud.githubusercontent.com/assets/23058301/20254034/b9a98b62-a9fe-11e6-8ff0-6c28426e316c.png)

Another 'bug' may be being able to put the same folder more than once in the library scan!

**Comment by theweavrs** [comment]
Try making a separate small folder some place else in your drive and putting some songs in their and then scanning that folder.
As I can see from the results, the player isn't scanning the folder at all.

**Comment by theweavrs** [comment]
About the drag/drop: It is not possible (yet) to drop folders. Only files are supported for the moment.

**Comment by MightyK1337** [comment]
This issue is present in Mobile too. I tried resetting the setting, selecting a small folder with very few songs, but it is still showing that nothing is available, along with the link to select folders again.

**Comment by theweavrs** [comment]
@MightyK1337 I am updating the package again with some changes and extended error reporting. Let's see if it works.

I cannot reproduce this issue at all. All my songs are loading and playing fine.

@DannyTalent If you have access to your PC, can you please go into your music folder and enter this in the search bar: "kind:music" (without quotes)? See if any results come up.

**Comment by DannyTalent** [comment]
Uhh, nope, nothing...

![image](https://cloud.githubusercontent.com/assets/23058301/20261432/af978a16-aa2b-11e6-86b6-2a31b2a5de49.png)

Still getting the same error...
![image](https://cloud.githubusercontent.com/assets/23058301/20261470/ecc04338-aa2b-11e6-8272-166992bf8960.png)

After this, "nothing baking"

**Comment by theweavrs** [comment]
I know where the problem is!! It is in the AQS query I was using to get all the music files from the directory. I will fix this right away and update!

**Comment by theweavrs** [comment]
@DannyTalent @MightyK1337 Fixed and updated! Go and check it out now! [Alpha-1.6.1](https://github.com/theweavrs/BreadPlayer/tree/v0.1.6.1-alpha)
